In [2]:
lis=["al",44,5.0]
for i in lis:
    print(i," ",type(i))


al   <class 'str'>
44   <class 'int'>
5.0   <class 'float'>


In [13]:
# id vector
import numpy as np
mat=[1,2,3]
a=np.array(mat)
print(a)
a.shape

[1 2 3]


(3,)

In [14]:
# 2d matrix
import numpy as np
mat=[[1,2,3], [1,2,3]]
a=np.array(mat)
print(a)
a.shape

[[1 2 3]
 [1 2 3]]


(2, 3)

In [16]:
## Slicing
import numpy as np
mat=[1,2,3]
a=np.array(mat)
print(a)
print(a[0:2])

[1 2 3]
[1 2]


In [20]:
## List addition
import numpy as np
mat=[1,2,3]
mat2=[4,5,5]
add= mat + mat2
print(add)

[1, 2, 3, 4, 5, 5]


In [27]:
import time

start = time.time()
print("Start time:", start)

mat = [1, 2, 3]
mat2 = [4, 5, 5]
add = []

for i, k in enumerate(mat):
    addition = mat[i] + mat2[i]
    add.append(addition)

print("Result:", add)

end = time.time()
print("End time:", end)

total_time = end - start
print("Total time to execute this program is:", total_time)


Start time: 1715496008.412191
Result: [5, 7, 8]
End time: 1715496008.412191
Total time to execute this program is: 0.0


In [28]:
# Vectorization
import time
import numpy as np
start=time.time()
mat=[1,2,3]
mat2=[4,5,5]
mat=np.array(mat)
mat2=np.array(mat2)
add= mat + mat2
print(add)
end=time.time()
print("Total time to execute this program is: ",(start-end))

[5 7 8]
Total time to execute this program is:  0.0


In [29]:
# Array Mutable

f=[2,5,7,89,9]
arr=np.array(f)
arr[3]=8
print(arr)

[2 5 7 8 9]


In [30]:
f=[2,5,7,89,9]
arr=np.array(f)
arr[0:2]=8
print(arr)

[ 8  8  7 89  9]


In [32]:
f=[2,5,7,89,9]
arr=np.array(f,dtype=np.int8)

In [33]:
f=[2,5,7,89,9]
arr=np.array(f)
print(f)

[2, 5, 7, 89, 9]


In [38]:
f=[[2,5,7,89,9],[3,4,5,5,6]]
arr=np.array(f)
print(arr)
print("")
print(arr.T)

[[ 2  5  7 89  9]
 [ 3  4  5  5  6]]

[[ 2  3]
 [ 5  4]
 [ 7  5]
 [89  5]
 [ 9  6]]


In [39]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [40]:
for i in range(0,10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [47]:
for i in range(0,10,2):
    print(i)
    print(type(i))

0
<class 'int'>
2
<class 'int'>
4
<class 'int'>
6
<class 'int'>
8
<class 'int'>


In [46]:
g=np.arange(0,12)
print(g)
print(type(g))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


In [58]:
# Create trable of 16
s=np.arange(16,1000,16)
print(s)

[ 16  32  48  64  80  96 112 128 144 160 176 192 208 224 240 256 272 288
 304 320 336 352 368 384 400 416 432 448 464 480 496 512 528 544 560 576
 592 608 624 640 656 672 688 704 720 736 752 768 784 800 816 832 848 864
 880 896 912 928 944 960 976 992]


In [61]:
g=np.linspace(0,12,1000)
print(g)

[ 0.          0.01201201  0.02402402  0.03603604  0.04804805  0.06006006
  0.07207207  0.08408408  0.0960961   0.10810811  0.12012012  0.13213213
  0.14414414  0.15615616  0.16816817  0.18018018  0.19219219  0.2042042
  0.21621622  0.22822823  0.24024024  0.25225225  0.26426426  0.27627628
  0.28828829  0.3003003   0.31231231  0.32432432  0.33633634  0.34834835
  0.36036036  0.37237237  0.38438438  0.3963964   0.40840841  0.42042042
  0.43243243  0.44444444  0.45645646  0.46846847  0.48048048  0.49249249
  0.5045045   0.51651652  0.52852853  0.54054054  0.55255255  0.56456456
  0.57657658  0.58858859  0.6006006   0.61261261  0.62462462  0.63663664
  0.64864865  0.66066066  0.67267267  0.68468468  0.6966967   0.70870871
  0.72072072  0.73273273  0.74474474  0.75675676  0.76876877  0.78078078
  0.79279279  0.8048048   0.81681682  0.82882883  0.84084084  0.85285285
  0.86486486  0.87687688  0.88888889  0.9009009   0.91291291  0.92492492
  0.93693694  0.94894895  0.96096096  0.97297297  0.

In [63]:
g=np.linspace(0,12,1000,retstep=True)
print(g)

(array([ 0.        ,  0.01201201,  0.02402402,  0.03603604,  0.04804805,
        0.06006006,  0.07207207,  0.08408408,  0.0960961 ,  0.10810811,
        0.12012012,  0.13213213,  0.14414414,  0.15615616,  0.16816817,
        0.18018018,  0.19219219,  0.2042042 ,  0.21621622,  0.22822823,
        0.24024024,  0.25225225,  0.26426426,  0.27627628,  0.28828829,
        0.3003003 ,  0.31231231,  0.32432432,  0.33633634,  0.34834835,
        0.36036036,  0.37237237,  0.38438438,  0.3963964 ,  0.40840841,
        0.42042042,  0.43243243,  0.44444444,  0.45645646,  0.46846847,
        0.48048048,  0.49249249,  0.5045045 ,  0.51651652,  0.52852853,
        0.54054054,  0.55255255,  0.56456456,  0.57657658,  0.58858859,
        0.6006006 ,  0.61261261,  0.62462462,  0.63663664,  0.64864865,
        0.66066066,  0.67267267,  0.68468468,  0.6966967 ,  0.70870871,
        0.72072072,  0.73273273,  0.74474474,  0.75675676,  0.76876877,
        0.78078078,  0.79279279,  0.8048048 ,  0.81681682,  0.8

In [ ]:
[4,5,6,6,6,7,5,5]
[4,5,6,6]
[3,4,5,6,6,6,7,7,5]
#max length=10
[4,5,6,6,6,7,5,5,0]
[4,5,6,6,0,0,0,0,0]

In [67]:
g=np.zeros((4,9))
print(g)

[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [68]:
g=np.ones((4,9))
print(g)

[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [75]:
g=np.eye(4,4,k=1)
print(g)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
